[package]
name = "mlem_egui_themes"
authors = ["Puk Bruinsma <puk@stupidplusplus.com>"]
version = "0.1.0"
edition = "2021"

[dependencies]
nih_plug_egui = { git = "https://github.com/robbert-vdh/nih-plug" }
